version: '3.1'
services:
  kura:
    networks:
      - iot_network
    image: eclipse/kura
    volumes:
      - kura-config:/opt/eclipse/kura
    command: /opt/eclipse/kura/kura
    expose:
      - 7043
    ports:
      - "443:443"
      - "7043:7043"

  postgres:
    networks:
      - iot_network
    image: postgres:latest
    environment:
      POSTGRES_USER: giotgrad03
      POSTGRES_PASSWORD: 7geWIkSB
      POSTGRES_DB: sensor_data.sql
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  db:
    networks:
      - iot_network
    container_name: db
    image: kapua/kapua-sql:${IMAGE_VERSION}
    ports:
      - "3306:3306"
  es:
    networks:
      - iot_network
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=kapua-datastore
      - discovery.type=single-node
      - transport.host=_site_
      - transport.ping_schedule=-1
      - transport.tcp.connect_timeout=30s
  events-broker:
    networks:
      - iot_network
    container_name: events-broker
    image: kapua/kapua-events-broker:${IMAGE_VERSION}
    ports:
      - "5672:5672"
  broker:
    networks:
      - iot_network
    container_name: broker
    image: kapua/kapua-broker:${IMAGE_VERSION}
    volumes:
      - kapua-data:/opt/eclipse/kapua
    expose:
      - 1884
    ports:
      - "1884:1883"
      - "8883:8883"
      - "61614:61614"
    depends_on:
      - db
      - es
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CRT
      - KAPUA_CA
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL

  kapua-console:
    networks:
      - iot_network
    container_name: kapua-console
    image: kapua/kapua-console:${IMAGE_VERSION}
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - broker
      - db
      - es
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
      - KAPUA_CONSOLE_URL
      - KAPUA_OPENID_JWT_ISSUER
      - KAPUA_OPENID_CLIENT_ID
      - KAPUA_OPENID_CLIENT_SECRET
      - KAPUA_OPENID_JWT_AUDIENCE
      - KAPUA_OPENID_AUTH_ENDPOINT
      - KAPUA_OPENID_TOKEN_ENDPOINT
      - KAPUA_OPENID_LOGOUT_ENDPOINT
      - KEYCLOAK_URL
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_REALM
  kapua-api:
    networks:
      - iot_network
    container_name: kapua-api
    image: kapua/kapua-api:${IMAGE_VERSION}
    expose:
      - 8081
    ports:
      - "8081:8080"
      - "8444:8443"
    depends_on:
      - broker
      - db
      - es
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
      - SWAGGER=${KAPUA_SWAGGER_ENABLE:-true}
  job-engine:
    networks:
      - iot_network
    container_name: job-engine
    image: kapua/kapua-job-engine:${IMAGE_VERSION}
    expose:
      - 8080
    depends_on:
      - broker
      - db
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSLd
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
  streamlit-app:
    expose:
      - 8043
    networks:
      - iot_network
    build: ./front
    ports:
      - "8043:8501"
    depends_on:
      - kapua-api
    volumes:
      - ./front:/dash
networks:
  iot_network:
    driver: bridge
volumes:
  kapua-data:
  kura-config:
  postgres-data:


